<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\Relations\BelongsTo;
use Illuminate\Database\Eloquent\Relations\BelongsToMany;
use Illuminate\Database\Eloquent\Relations\HasMany;
use Illuminate\Support\Str;

class Contest extends Model
{
    public const STATUS_DRAFT = 'draft';

    public const STATUS_PUBLISHED = 'published';

    public const STATUS_CANCELLED = 'cancelled';

    public const STATUSES = [self::STATUS_DRAFT, self::STATUS_PUBLISHED, self::STATUS_CANCELLED];

    /** Mellow-staff-curated, platform-wide — today's original (and still default) shape. */
    public const CONTEST_TYPE_GENERAL = 'general';

    /** Auto-generated by GenerateDailyContest, one per calendar day, platform-wide. Never hand-created. */
    public const CONTEST_TYPE_DAILY = 'daily';

    /** Mellow-staff-curated, tied to one company/drive — visible only to colleges that drive is mapped+approved to. */
    public const CONTEST_TYPE_COMPANY = 'company';

    /** A college TPO's own private practice contest for their own students only. Never rated. */
    public const CONTEST_TYPE_TPO_MOCK = 'tpo_mock';

    /** A company hiring tenant's own proctored assessment, tied to one of their job openings. Never rated, visible only to invited candidates — see isVisibleToUser(). */
    public const CONTEST_TYPE_COMPANY_HIRING = 'company_hiring';

    /**
     * Mellow-staff-curated, NOT tied to any company/drive — the sourcing
     * event for the shared Talent Pool marketplace (see
     * App\Models\TalentPoolCandidate, App\Services\TalentPoolQualificationService).
     * Never rated (these are qualification tests, not rating events).
     * Targeted via `audience_scope` (see that column's migration) rather
     * than a drive's college mappings: all students, specific colleges
     * (`contest_colleges`, same pivot `company` contests use), or only
     * college-less "Mellow Direct" users.
     */
    public const CONTEST_TYPE_TALENT_POOL = 'talent_pool';

    public const CONTEST_TYPES = [
        self::CONTEST_TYPE_GENERAL,
        self::CONTEST_TYPE_DAILY,
        self::CONTEST_TYPE_COMPANY,
        self::CONTEST_TYPE_TPO_MOCK,
        self::CONTEST_TYPE_COMPANY_HIRING,
        self::CONTEST_TYPE_TALENT_POOL,
    ];

    public const AUDIENCE_SCOPE_ALL = 'all';

    public const AUDIENCE_SCOPE_COLLEGE = 'college';

    public const AUDIENCE_SCOPE_DIRECT = 'direct';

    public const AUDIENCE_SCOPES = [
        self::AUDIENCE_SCOPE_ALL,
        self::AUDIENCE_SCOPE_COLLEGE,
        self::AUDIENCE_SCOPE_DIRECT,
    ];

    protected $fillable = [
        'title',
        'slug',
        'description',
        'start_at',
        'end_at',
        'is_rated',
        'status',
        'finalized_at',
        'created_by',
        'contest_type',
        'daily_key',
        'is_auto_generated',
        'company_id',
        'placement_drive_id',
        'owning_college_id',
        'owning_company_id',
        'audience_scope',
        'qualifying_score_percent',
    ];

    protected function casts(): array
    {
        return [
            'start_at' => 'datetime',
            'end_at' => 'datetime',
            'is_rated' => 'boolean',
            'finalized_at' => 'datetime',
            'is_auto_generated' => 'boolean',
            'qualifying_score_percent' => 'decimal:2',
        ];
    }

    public function getRouteKeyName(): string
    {
        return 'slug';
    }

    public function contestProblems(): HasMany
    {
        return $this->hasMany(ContestProblem::class);
    }

    public function participants(): HasMany
    {
        return $this->hasMany(ContestParticipant::class);
    }

    public function contestSubmissions(): HasMany
    {
        return $this->hasMany(ContestSubmission::class);
    }

    public function createdBy(): BelongsTo
    {
        return $this->belongsTo(User::class, 'created_by');
    }

    public function company(): BelongsTo
    {
        return $this->belongsTo(Company::class);
    }

    public function placementDrive(): BelongsTo
    {
        return $this->belongsTo(PlacementDrive::class);
    }

    public function owningCollege(): BelongsTo
    {
        return $this->belongsTo(College::class, 'owning_college_id');
    }

    public function owningCompany(): BelongsTo
    {
        return $this->belongsTo(Company::class, 'owning_company_id');
    }

    /**
     * A `company` contest's own explicit college targeting (see the
     * contest_colleges migration docblock) — Ops picks a subset of the
     * drive's live-mapped colleges rather than the contest always going to
     * every college the drive happens to be mapped to.
     */
    public function colleges(): BelongsToMany
    {
        return $this->belongsToMany(College::class, 'contest_colleges');
    }

    public function hasStarted(): bool
    {
        return $this->start_at->isPast();
    }

    public function hasEnded(): bool
    {
        return $this->end_at->isPast();
    }

    public function isLive(): bool
    {
        return $this->hasStarted() && ! $this->hasEnded();
    }

    public function isPublished(): bool
    {
        return $this->status === self::STATUS_PUBLISHED;
    }

    public function isCompanyContest(): bool
    {
        return $this->contest_type === self::CONTEST_TYPE_COMPANY;
    }

    public function isTpoMock(): bool
    {
        return $this->contest_type === self::CONTEST_TYPE_TPO_MOCK;
    }

    public function isCompanyHiring(): bool
    {
        return $this->contest_type === self::CONTEST_TYPE_COMPANY_HIRING;
    }

    public function isDaily(): bool
    {
        return $this->contest_type === self::CONTEST_TYPE_DAILY;
    }

    public function isTalentPool(): bool
    {
        return $this->contest_type === self::CONTEST_TYPE_TALENT_POOL;
    }

    /**
     * The single source of truth for "can a student from college X even see
     * this contest" — general/daily contests are platform-wide, a tpo_mock
     * contest is visible only to its own owning college, and a company
     * contest requires BOTH: the college was explicitly picked by Ops for
     * THIS contest (contest_colleges — see that migration's docblock; a
     * drive can be live at several colleges but a contest may target only
     * some of them) AND the drive is still actually live-mapped to that
     * college right now (so a college that later backs out of the drive
     * entirely loses contest access automatically, even if it was
     * previously hand-picked here). Reused by ContestController's index
     * (filtering a collection, not a query — contest counts are small
     * enough that N+1 here is not a real concern) and by
     * show()/register()/leaderboard() for the single-contest case.
     */
    public function isVisibleToCollege(?int $collegeId): bool
    {
        return match ($this->contest_type) {
            self::CONTEST_TYPE_TPO_MOCK => $collegeId !== null && $this->owning_college_id === $collegeId,
            self::CONTEST_TYPE_COMPANY => $collegeId !== null && $this->placement_drive_id !== null
                && $this->colleges()->where('colleges.id', $collegeId)->exists()
                && DriveCollegeMapping::query()
                    ->where('placement_drive_id', $this->placement_drive_id)
                    ->where('college_id', $collegeId)
                    ->where('status', DriveCollegeMapping::STATUS_APPROVED)
                    ->where('is_active', true)
                    ->exists(),
            // No drive/mapping involved at all — Mellow targets colleges (or
            // college-less "direct" users) directly for its own scouting
            // assessment. `college_ids` here is Ops's explicit pick
            // (contest_colleges), never derived from any mapping.
            self::CONTEST_TYPE_TALENT_POOL => match ($this->audience_scope) {
                self::AUDIENCE_SCOPE_COLLEGE => $collegeId !== null && $this->colleges()->where('colleges.id', $collegeId)->exists(),
                self::AUDIENCE_SCOPE_DIRECT => $collegeId === null,
                default => true, // AUDIENCE_SCOPE_ALL (or unset — treat as platform-wide)
            },
            default => true,
        };
    }

    /**
     * For the Ops contest list/create-flow: how many colleges Ops picked for
     * this `company` contest (`selected`), how many of those are actually
     * still live right now (`live` — the two can diverge if a college backs
     * out of the drive after being selected here), and how many more
     * colleges have a pending drive-mapping proposal that could later be
     * added (`pending`). Null for any other contest type (the concept
     * doesn't apply — general/daily are platform-wide, tpo_mock is
     * single-college by definition). Distinct from isVisibleToCollege()
     * above (a yes/no check for one college) — this is the aggregate Ops
     * needs to notice "nobody will ever see this contest" before it's too late.
     */
    public function visibilityCollegeSummary(): ?array
    {
        if (! $this->isCompanyContest() || $this->placement_drive_id === null) {
            return null;
        }

        $selectedCollegeIds = $this->colleges()->pluck('colleges.id');

        $mappings = DriveCollegeMapping::where('placement_drive_id', $this->placement_drive_id)->get();
        $liveDriveCollegeIds = $mappings
            ->filter(fn (DriveCollegeMapping $m) => $m->status === DriveCollegeMapping::STATUS_APPROVED && $m->is_active)
            ->pluck('college_id');

        return [
            'selected' => $selectedCollegeIds->count(),
            'live' => $selectedCollegeIds->intersect($liveDriveCollegeIds)->count(),
            'pending' => $mappings->where('status', DriveCollegeMapping::STATUS_PENDING)->count(),
        ];
    }

    /**
     * The single source of truth for "can this specific user even see this
     * contest" — delegates to isVisibleToCollege() for every existing type
     * (general/daily/company/tpo_mock all stay college-scoped, byte-identical
     * behavior), and only branches for the new company_hiring type, where a
     * candidate isn't tenant-scoped by college at all. Three independent ways
     * in: (1) explicitly invited (a ContestParticipant row a recruiter
     * creates via CompanyContestController::inviteCandidates()), (2) the
     * candidate's own college approved the underlying job opening (see (3)
     * below the college-wise proposal-and-approval flow), or (3) the company
     * marked the opening open to every registered candidate platform-wide
     * (PlacementDrive::is_open_to_all). Reused by every call site
     * isVisibleToCollege() used to serve directly (ContestController,
     * ContestSubmissionController).
     */
    public function isVisibleToUser(User $user): bool
    {
        if ($this->contest_type === self::CONTEST_TYPE_COMPANY_HIRING) {
            if ($this->participants()->where('user_id', $user->id)->exists()) {
                return true;
            }

            // The company opened this job opening to every registered
            // candidate on the platform — deliberately NOT gated on
            // $user->college_id being set, unlike the college-approved check
            // below: this must also cover college-less "Mellow Direct"
            // users, who could never pass that check no matter what.
            if ($this->placementDrive?->is_open_to_all) {
                return true;
            }

            // A company proposed this contest's underlying job opening to
            // the user's own college and that college's TPO approved it
            // (see CompanyDriveController::proposeToColleges(), the same
            // pending-mapping-and-approval mechanism Mellow Ops uses for
            // catalog drives) — no per-candidate invite needed in that case,
            // any eligible student at an approved college can self-register
            // exactly like any other visible contest. Queried directly
            // against DriveCollegeMapping rather than the contest_colleges
            // pivot: unlike a Mellow-curated `company` contest, a company's
            // own contest has no "Ops further narrows which of the mapped
            // colleges see this particular round" concept to support.
            return $user->college_id !== null
                && $this->placement_drive_id !== null
                && DriveCollegeMapping::query()
                    ->where('placement_drive_id', $this->placement_drive_id)
                    ->where('college_id', $user->college_id)
                    ->where('status', DriveCollegeMapping::STATUS_APPROVED)
                    ->where('is_active', true)
                    ->exists();
        }

        return $this->isVisibleToCollege($user->college_id);
    }

    /**
     * Shared by AdminContestController (general/company) and
     * TpoContestController (tpo_mock) so the slugging rule lives in exactly
     * one place instead of two near-identical private methods.
     */
    public static function uniqueSlug(string $title): string
    {
        $base = Str::slug($title) ?: 'contest';
        $slug = $base;
        $suffix = 1;

        while (self::where('slug', $slug)->exists()) {
            $suffix++;
            $slug = "{$base}-{$suffix}";
        }

        return $slug;
    }
}
