<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\Schema;

/**
 * Widens Contest beyond the single Mellow-curated "general" shape into four
 * kinds (see App\Models\Contest::CONTEST_TYPES):
 *  - general: unchanged today's behavior, Mellow-staff-curated, platform-wide.
 *  - daily: auto-generated by App\Console\Commands\GenerateDailyContest,
 *    one per calendar day, platform-wide. `daily_key` is the real
 *    concurrency-safe idempotency guard (a unique index, not just an
 *    application-level check) — two overlapping scheduler fires racing to
 *    create the same day's contest will have one hit a duplicate-key error
 *    instead of both succeeding.
 *  - company: Mellow-staff-curated, tied to a specific company/drive so its
 *    visibility can be derived from that drive's DriveCollegeMapping rows
 *    (only students at colleges where the drive is mapped+approved ever see
 *    it) — see Contest::isVisibleToCollege().
 *  - tpo_mock: a college TPO's own private practice contest for their own
 *    students only (`owning_college_id`), never rated (enforced in
 *    TpoContestController, not here) and never visible to any other college.
 *
 * `contest_type` stays a plain string (like `status` already is on this
 * table) rather than a real MySQL ENUM — no ALTER-TABLE-ENUM migration
 * needed the next time a type is added, matching this table's own existing
 * convention.
 */
return new class extends Migration
{
    public function up(): void
    {
        Schema::table('contests', function (Blueprint $table) {
            $table->string('contest_type')->default('general')->after('status');
            $table->string('daily_key', 10)->nullable()->unique()->after('contest_type');
            $table->boolean('is_auto_generated')->default(false)->after('daily_key');
            $table->foreignId('company_id')->nullable()->after('is_auto_generated')->constrained()->nullOnDelete();
            $table->foreignId('placement_drive_id')->nullable()->after('company_id')->constrained()->nullOnDelete();
            $table->foreignId('owning_college_id')->nullable()->after('placement_drive_id')->constrained('colleges')->nullOnDelete();

            $table->index('contest_type');
            $table->index('owning_college_id');
        });
    }

    public function down(): void
    {
        Schema::table('contests', function (Blueprint $table) {
            $table->dropForeign(['company_id']);
            $table->dropForeign(['placement_drive_id']);
            $table->dropForeign(['owning_college_id']);
            $table->dropColumn(['contest_type', 'daily_key', 'is_auto_generated', 'company_id', 'placement_drive_id', 'owning_college_id']);
        });
    }
};
