<?php

namespace Database\Seeders;

use App\Models\Problem;
use Illuminate\Database\Seeder;
use RuntimeException;

/**
 * Seeds 100 additional, well-known DSA interview problems (curated from the
 * usual reputable sources — LeetCode's Blind 75 / NeetCode 150, Striver's
 * SDE sheet, GeeksforGeeks' must-do lists — covering arrays/hashing,
 * strings, binary search, sliding window, stacks, array-represented graphs,
 * matrices, dynamic programming, and backtracking) on top of the original
 * five seeded by ProblemSeeder.
 *
 * Unlike ProblemSeeder, the catalog data itself isn't hand-written PHP here:
 * it lives in data/dsa_100_problems.json, generated by a build script whose
 * reference-solution implementations were actually executed to produce every
 * expected_output (see the generator sources kept alongside this repo's
 * tooling) rather than computed by hand — the same structured
 * function-signature + test-case format ProblemSeeder uses, just sourced
 * from data instead of inline arrays given the volume.
 */
class DsaHundredProblemSeeder extends Seeder
{
    public function run(): void
    {
        $path = __DIR__.'/data/dsa_100_problems.json';

        if (! file_exists($path)) {
            throw new RuntimeException("DsaHundredProblemSeeder: missing data file at {$path}");
        }

        $problems = json_decode(file_get_contents($path), true, flags: JSON_THROW_ON_ERROR);

        foreach ($problems as $spec) {
            $testCases = $spec['test_cases'];
            unset($spec['test_cases']);

            $problem = Problem::updateOrCreate(['slug' => $spec['slug']], $spec);

            $problem->testCases()->delete();
            foreach ($testCases as $index => $testCase) {
                $problem->testCases()->create([...$testCase, 'display_order' => $index]);
            }
        }
    }
}
