<?php

namespace Database\Seeders;

/**
 * The authored Vocabulary Sprint word library: 8 decks x 20 words.
 *
 * Every entry is written to a few rules, and VocabularyWordBankTest enforces
 * the ones a machine can check:
 *
 *  - meaning: a lower-case phrase that reads naturally after "means", never
 *    contains the word itself.
 *  - example: ONE natural sentence that contains the headword exactly as
 *    written (so the sentence-blank question can blank it out).
 *  - synonyms: plain words, never another headword in the library.
 *  - distractors: exactly three wrong answers for the sentence-blank question.
 *    Each must be definitely wrong in that sentence — the sentence carries a
 *    cue (a contradiction, a preposition, a clause) that only the headword
 *    satisfies — and none may be a synonym of the answer.
 *  - no two words in the library may mean nearly the same thing, because a
 *    "which meaning?" question with two defensible answers is a broken question.
 *    Words that students genuinely mix up (the confusing-pairs deck) are the
 *    deliberate exception: there the partner IS the point, and each meaning is
 *    kept sharply distinct.
 *
 * Row layout: [word, part of speech, meaning, example, synonyms, distractors,
 * look-alike partner, usage note, level override].
 */
final class VocabularyWordBank
{
    /** @return array<int, array<string, mixed>> every word, in deck-path order, ready for updateOrCreate */
    public static function words(): array
    {
        $decks = [
            'workplace-essentials' => ['beginner', self::workplaceEssentials()],
            'interview-power-words' => ['intermediate', self::interviewPowerWords()],
            'communication-and-persuasion' => ['intermediate', self::communicationAndPersuasion()],
            'tech-and-engineering' => ['intermediate', self::techAndEngineering()],
            'business-and-finance' => ['intermediate', self::businessAndFinance()],
            'confusing-pairs' => ['intermediate', self::confusingPairs()],
            'phrasal-verbs-and-idioms' => ['intermediate', self::phrasalVerbsAndIdioms()],
            'reasoning-and-verbal' => ['advanced', self::reasoningAndVerbal()],
        ];

        $words = [];
        foreach ($decks as $slug => [$defaultLevel, $rows]) {
            foreach ($rows as $order => $row) {
                $words[] = [
                    'deck' => $slug,
                    'word' => $row[0],
                    'part_of_speech' => $row[1],
                    'level' => $row[8] ?? $defaultLevel,
                    'meaning' => $row[2],
                    'example' => $row[3],
                    'synonyms' => $row[4],
                    'distractors' => $row[5],
                    'pair_word' => $row[6] ?? null,
                    'note' => $row[7] ?? null,
                    'sort_order' => $order + 1,
                ];
            }
        }

        return $words;
    }

    private static function workplaceEssentials(): array
    {
        return [
            ['deadline', 'noun', 'the date or time by which something must be finished',
                'The deadline for submitting the report is Friday at 5 PM.',
                ['due date', 'cut-off'], ['holiday', 'salary', 'venue']],
            ['agenda', 'noun', 'a list of the topics to be discussed at a meeting',
                'Please read the agenda before the meeting so you know what will be discussed.',
                ['programme', 'schedule'], ['invoice', 'passport', 'vacancy'],
                null, 'The agenda is written before a meeting; the minutes are written after it.'],
            ['minutes', 'noun', 'the written record of what was said and decided at a meeting',
                'Anita will write up the minutes and email them to the team after the meeting.',
                ['meeting notes', 'record'], ['uniforms', 'vacancies', 'umbrellas'],
                null, 'Always plural when it means meeting notes.'],
            ['postpone', 'verb', 'to move an event to a later time',
                'We had to postpone the launch because the server was not ready.',
                ['delay', 'defer'], ['accelerate', 'celebrate', 'imitate']],
            ['delegate', 'verb', 'to give part of your work or authority to someone else',
                'A good manager learns to delegate tasks instead of doing everything alone.',
                ['assign', 'hand over'], ['decorate', 'imitate', 'evaporate'],
                null, 'As a noun it means a person chosen to represent others, and is said differently.'],
            ['remind', 'verb', 'to help someone remember to do something',
                'Can you remind me to send the invoice before I leave today?',
                ['prompt', 'jog the memory of'], ['forbid', 'punish', 'borrow']],
            ['urgent', 'adjective', 'needing attention immediately',
                'I have an urgent request from the client that cannot wait until Monday.',
                ['pressing', 'critical'], ['optional', 'ancient', 'elegant']],
            ['priority', 'noun', 'something that is more important than other things and should be done first',
                'Fixing the login bug is our top priority this week.',
                ['first concern', 'main focus'], ['hobby', 'ceremony', 'souvenir']],
            ['feedback', 'noun', 'comments about how well someone is doing something, to help them improve',
                'My mentor gave me honest feedback on my presentation.',
                ['comments', 'critique'], ['luggage', 'furniture', 'scenery'],
                null, 'Uncountable: say "some feedback", never "a feedback".'],
            ['attend', 'verb', 'to be present at an event or meeting',
                'All team members are expected to attend the Monday stand-up.',
                ['be present at', 'go to'], ['pretend', 'exceed', 'relieve']],
            ['approve', 'verb', 'to officially say that a plan or request can go ahead',
                'Your manager must approve your leave request before you travel.',
                ['authorise', 'sanction'], ['dissolve', 'borrow', 'blame']],
            ['available', 'adjective', 'free to be used, or free to talk or meet',
                'Are you available for a quick call at 3 PM?',
                ['free', 'accessible'], ['generous', 'temporary', 'fragile']],
            ['circulate', 'verb', 'to send something to a group of people',
                'Please circulate the final report to everyone in the department by noon.',
                ['distribute', 'pass around'], ['cancel', 'rinse', 'accuse']],
            ['proofread', 'verb', 'to read a text carefully to find and correct mistakes',
                'Always proofread your email before you click send.',
                ['check', 'correct'], ['overhear', 'outrun', 'undermine']],
            ['escalate', 'verb', 'to pass a problem to someone with more authority',
                'If the client is still unhappy, we will escalate the issue to the senior manager.',
                ['refer upward', 'raise'], ['ignore', 'solve', 'forget']],
            ['acknowledge', 'verb', 'to say that you have received or noticed something',
                'Please acknowledge this email so I know you have received it.',
                ['confirm receipt of', 'recognise'], ['forbid', 'inherit', 'stretch']],
            ['concise', 'adjective', 'giving all the important information in very few words',
                'Keep your email concise; busy managers rarely read long messages.',
                ['brief', 'succinct'], ['lengthy', 'elaborate', 'detailed']],
            ['reimburse', 'verb', 'to pay back money that someone has spent',
                "The company will reimburse your travel expenses within two weeks.",
                ['repay', 'refund'], ['exaggerate', 'abandon', 'dilute']],
            ['onboarding', 'noun', 'the process of helping a new employee settle into a job',
                'The HR team runs a week-long onboarding for every new joiner.',
                ['induction', 'orientation'], ['retirement', 'vacation', 'inspection']],
            ['attachment', 'noun', 'a file that is sent together with an email',
                'I forgot the attachment, so I am resending the email with the file.',
                ['enclosure', 'added file'], ['vacancy', 'ceiling', 'landscape']],
        ];
    }

    private static function interviewPowerWords(): array
    {
        return [
            ['innovative', 'adjective', 'using new ideas or methods',
                'Our startup is looking for innovative thinkers who can solve problems in new ways.',
                ['original', 'inventive'], ['traditional', 'conventional', 'routine']],
            ['initiative', 'noun', 'the ability to start doing something useful without being asked',
                'She showed great initiative by fixing the broken process without waiting for instructions.',
                ['drive', 'enterprise'], ['obedience', 'hesitation', 'permission'],
                null, 'Interviewers love hearing "I took the initiative to…".'],
            ['accountable', 'adjective', 'responsible for your actions and ready to explain them',
                'I take ownership of my work and hold myself accountable for the results.',
                ['answerable', 'responsible'], ['flexible', 'creative', 'mysterious']],
            ['resilient', 'adjective', 'able to recover quickly after difficulties',
                'After my first interview went badly, I stayed resilient and prepared harder for the next one.',
                ['tough', 'hardy'], ['discouraged', 'fragile', 'bitter']],
            ['adaptable', 'adjective', 'able to adjust easily to new situations',
                'Startups need adaptable people who can switch tasks when priorities change.',
                ['flexible', 'adjustable'], ['rigid', 'stubborn', 'unwilling']],
            ['meticulous', 'adjective', 'very careful and exact about small details',
                'Her meticulous testing caught a bug that three other engineers had missed.',
                ['painstaking', 'precise'], ['hasty', 'careless', 'generous']],
            ['spearhead', 'verb', 'to lead an important activity or effort',
                'I volunteered to spearhead the campus recruitment drive for our club.',
                ['head', 'pioneer'], ['dismiss', 'overhear', 'exhaust']],
            ['streamline', 'verb', 'to make a process simpler and quicker by removing unnecessary steps',
                'I proposed a plan to streamline the approval process and cut waiting time from five days to one.',
                ['simplify', 'optimise'], ['complicate', 'duplicate', 'interrupt']],
            ['leverage', 'verb', 'to use something you already have to get an advantage',
                'I would leverage my internship experience to ramp up quickly in this role.',
                ['exploit', 'capitalise on'], ['ignore', 'waste', 'hide'],
                null, 'Very common in business English, but use it sparingly in speech.'],
            ['strategic', 'adjective', 'planned carefully to achieve a long-term goal',
                'I made a strategic decision to learn SQL first, because most roles I want require it.',
                ['calculated', 'planned'], ['careless', 'random', 'hasty']],
            ['ambitious', 'adjective', 'having a strong desire to succeed and achieve a lot',
                'I am ambitious: I want to grow from a junior developer into a team leader.',
                ['aspiring', 'driven'], ['content', 'lazy', 'timid']],
            ['articulate', 'adjective', 'able to express ideas clearly and effectively',
                'The panel noticed that she was articulate and explained complex ideas in simple words.',
                ['fluent', 'expressive'], ['confused', 'hesitant', 'silent'],
                null, 'Also a verb (to express clearly), pronounced differently: "ar-TIK-yoo-late".'],
            ['proficient', 'adjective', 'having the skill and training to do something to a high standard',
                'I am proficient in Python and have used it in two internship projects.',
                ['skilled', 'competent'], ['anxious', 'generous', 'jealous']],
            ['approachable', 'adjective', 'friendly and easy to talk to',
                'Managers prefer team members who are approachable and open to questions.',
                ['friendly', 'welcoming'], ['distant', 'hostile', 'secretive']],
            ['punctual', 'adjective', 'arriving or doing things at the agreed time',
                "Being punctual for the interview shows that you respect the interviewer's time.",
                ['prompt', 'on time'], ['talkative', 'generous', 'curious']],
            ['collaborate', 'verb', 'to work together with others to achieve something',
                'At college I learned to collaborate with students from other branches on hackathon projects.',
                ['cooperate', 'team up'], ['hibernate', 'evaporate', 'orbit']],
            ['versatile', 'adjective', 'able to do many different kinds of things well',
                'I want to be a versatile developer who can work on both front-end and back-end tasks.',
                ['all-round', 'multi-skilled'], ['narrow', 'limited', 'fragile']],
            ['mentor', 'noun', 'an experienced person who advises and guides someone less experienced',
                'My college professor became my mentor and helped me plan my career.',
                ['guide', 'adviser'], ['rival', 'tenant', 'customer'],
                null, 'Can also be a verb: "She mentors two juniors."'],
            ['demonstrate', 'verb', 'to show clearly that you have a skill or quality',
                'I built a final-year project to demonstrate that I can design, build and test a full application.',
                ['show', 'prove'], ['conceal', 'deny', 'regret']],
            ['contribute', 'verb', 'to give your time, ideas or effort to help achieve something',
                'I am keen to contribute to open-source projects and learn from the community.',
                ['add', 'chip in'], ['retire', 'pretend', 'vanish']],
        ];
    }

    private static function communicationAndPersuasion(): array
    {
        return [
            ['tactful', 'adjective', 'careful not to upset or offend people when you speak',
                'She gave tactful feedback that pointed out the problem without hurting his feelings.',
                ['sensitive', 'considerate'], ['blunt', 'rude', 'sarcastic']],
            ['cliché', 'noun', 'an overused phrase that has lost its force',
                'Saying "I am a hard worker" is a cliché that interviewers hear every day.',
                ['stock phrase', 'platitude'], ['diploma', 'vacancy', 'contract'],
                null, 'Often written "cliche" without the accent, and that is fine.'],
            ['assertive', 'adjective', 'confident and direct in saying what you want, without being aggressive',
                'Being assertive means stating your opinion clearly while still respecting others.',
                ['confident', 'self-assured'], ['timid', 'hostile', 'indifferent'],
                null, 'Assertive is not the same as aggressive — it respects the other person.'],
            ['convey', 'verb', 'to communicate an idea, feeling or piece of information',
                'Your tone of voice can convey confidence even when you feel nervous.',
                ['communicate', 'express'], ['absorb', 'purchase', 'inherit']],
            ['elaborate', 'verb', 'to give more details about something',
                'Could you elaborate on your role in the project and what you personally built?',
                ['expand', 'explain further'], ['insist', 'depend', 'rely'],
                null, 'Also an adjective meaning detailed and complicated: an elaborate plan.'],
            ['rapport', 'noun', 'a close, friendly connection between people who understand each other',
                'A warm greeting and a smile help you build rapport with the interviewer.',
                ['bond', 'connection'], ['stamina', 'vocabulary', 'revenue'],
                null, 'The final "t" is silent: "ra-POR".'],
            ['negotiate', 'verb', 'to discuss something formally in order to reach an agreement',
                'You can negotiate your starting salary politely if you know your market value.',
                ['bargain', 'haggle'], ['imitate', 'abandon', 'decorate']],
            ['persuade', 'verb', 'to make someone agree to do or believe something by giving good reasons',
                'I used simple data to persuade my team to try the new tool.',
                ['convince', 'win over'], ['accuse', 'describe', 'mention']],
            ['highlight', 'verb', 'to draw special attention to something important',
                'In your resume, highlight achievements that show real results, not just duties.',
                ['stress', 'spotlight'], ['bury', 'hide', 'forget']],
            ['ambiguous', 'adjective', 'having more than one possible meaning, so not clear',
                "Avoid ambiguous words like 'soon' in emails; give an exact date instead.",
                ['unclear', 'vague'], ['precise', 'polite', 'formal']],
            ['constructive', 'adjective', 'helpful and aimed at improving something',
                'I welcome constructive criticism because it shows me how to improve.',
                ['helpful', 'positive'], ['destructive', 'hostile', 'pointless']],
            ['paraphrase', 'verb', 'to say the same thing again using different words',
                "If a question is unclear, paraphrase it back to the interviewer to check you understood.",
                ['reword', 'restate'], ['ignore', 'delete', 'forbid']],
            ['reiterate', 'verb', 'to say something again, usually to be sure it is understood',
                'At the end of the call, reiterate the next steps so nobody is confused.',
                ['repeat', 'restate firmly'], ['contradict', 'forget', 'invent']],
            ['etiquette', 'noun', 'the polite manners people expect in a particular situation',
                'Good email etiquette says you should greet the reader and reply within one working day.',
                ['manners', 'protocol'], ['software', 'hardware', 'weather']],
            ['empathy', 'noun', "the ability to understand and share another person's feelings",
                'Good customer support starts with empathy for the person who is frustrated.',
                ['understanding', 'compassion'], ['suspicion', 'profit', 'authority']],
            ['nuance', 'noun', 'a very small difference in meaning, tone or feeling',
                'Translation tools often miss the nuance in a polite refusal.',
                ['subtlety', 'shade of meaning'], ['volume', 'budget', 'scenery'],
                null, null, 'advanced'],
            ['gist', 'noun', 'the main idea of something, without the details',
                'I did not catch every word, but I got the gist, which was that the exam had moved to Monday.',
                ['essence', 'general idea'], ['refund', 'uniform', 'signature']],
            ['jargon', 'noun', 'special words used by one profession that outsiders find hard to understand',
                'Avoid technical jargon when you explain your project to a non-technical interviewer.',
                ['technical language', 'buzzwords'], ['politeness', 'scenery', 'furniture']],
            ['concede', 'verb', 'to admit that something is true or that the other side is right',
                "Be willing to concede a point when the other person's data is stronger than yours.",
                ['admit', 'yield'], ['contest', 'defend', 'ignore'],
                null, null, 'advanced'],
            ['tone', 'noun', 'the way your voice or writing sounds, which shows your attitude',
                'The words in the email were polite, but the tone felt cold.',
                ['manner', 'attitude'], ['length', 'spelling', 'margin']],
        ];
    }

    private static function techAndEngineering(): array
    {
        return [
            ['scalable', 'adjective', 'able to handle more users or data without breaking down',
                'We chose a cloud database because it is scalable as our user base grows.',
                ['expandable', 'growth-ready'], ['limited', 'obsolete', 'temporary']],
            ['robust', 'adjective', 'strong and able to keep working in difficult conditions',
                'Our application must be robust: it has to handle invalid input without crashing.',
                ['sturdy', 'solid'], ['fragile', 'unstable', 'weak']],
            ['deploy', 'verb', 'to release software so that users can start using it',
                'The team will deploy the new version to production on Saturday night.',
                ['release', 'ship'], ['delete', 'design', 'debate']],
            ['debug', 'verb', 'to find and fix errors in a program',
                'It took me three hours to debug a single missing semicolon.',
                ['troubleshoot', 'fix'], ['purchase', 'celebrate', 'abandon']],
            ['refactor', 'verb', 'to rewrite code so it is cleaner without changing what it does',
                'Before adding new features, we need to refactor this messy function.',
                ['restructure', 'clean up'], ['photocopy', 'announce', 'reward']],
            ['latency', 'noun', 'the delay between sending a request and getting the response',
                'Users on slow networks notice high latency when a page takes seconds to respond.',
                ['lag', 'delay'], ['capacity', 'popularity', 'storage']],
            ['bottleneck', 'noun', 'a point in a process where progress slows because capacity is limited',
                'The database was the bottleneck that slowed the entire system.',
                ['choke point', 'obstruction'], ['shortcut', 'advantage', 'reward']],
            ['iterate', 'verb', 'to repeat a process again and again, improving it each time',
                'Good engineers iterate quickly: they build, test, learn and improve.',
                ['repeat', 'refine'], ['retire', 'hibernate', 'imitate']],
            ['legacy', 'adjective', 'old, still in use, and usually hard to change',
                'Many banks still run on legacy systems written decades ago.',
                ['inherited', 'old-style'], ['futuristic', 'experimental', 'trendy'],
                null, 'As a noun it also means something handed down from the past: a legacy.'],
            ['redundancy', 'noun', 'extra copies or parts kept so that one failure does not stop everything',
                'Hospitals add redundancy to critical systems so one failure does not stop everything.',
                ['backup capacity', 'failover'], ['pollution', 'ambiguity', 'hostility'],
                null, 'In British English it can also mean losing a job because it is no longer needed.'],
            ['compatible', 'adjective', 'able to work together with another system without problems',
                'This app is not compatible with older versions of Android.',
                ['interoperable', 'workable together'], ['affordable', 'responsible', 'suspicious']],
            ['prototype', 'noun', 'an early, simple version of a product used to test an idea',
                'We built a rough prototype in two days to test the idea with real users.',
                ['early model', 'mock-up'], ['invoice', 'warranty', 'slogan']],
            ['integrate', 'verb', 'to combine two or more things so that they work together',
                'Our team had to integrate the payment gateway with the existing website.',
                ['combine', 'merge'], ['dismiss', 'accuse', 'complain']],
            ['encrypt', 'verb', 'to turn data into a secret code so unauthorised people cannot read it',
                'Always encrypt passwords before storing them in a database.',
                ['encode', 'scramble'], ['advertise', 'photograph', 'publish']],
            ['maintainable', 'adjective', 'easy to understand, fix and update over time',
                'Clear names and small functions keep code maintainable for the next developer.',
                ['easy to update', 'sustainable'], ['profitable', 'expensive', 'fashionable']],
            ['constraint', 'noun', 'a limit or restriction on what you can do',
                'Our biggest constraint was time; we had only two weeks to ship.',
                ['limitation', 'restriction'], ['advantage', 'reward', 'opinion']],
            ['verify', 'verb', 'to check that something is true or correct',
                'Please verify your email address by clicking the link we sent you.',
                ['check', 'validate'], ['invent', 'exaggerate', 'inherit']],
            ['benchmark', 'verb', 'to measure how well something performs by comparing it with a standard',
                'Before choosing a database, we ran tests to benchmark three options.',
                ['measure against', 'test against'], ['applaud', 'forgive', 'digest'],
                null, 'Also a noun: the standard you compare against.'],
            ['dependency', 'noun', 'something your work relies on, such as a library or another team',
                "The release is blocked by a dependency on another team's API.",
                ['reliance', 'prerequisite'], ['celebration', 'holiday', 'uniform']],
            ['automate', 'verb', 'to make a task run by itself using machines or software',
                'I wrote a script to automate the daily report instead of copying data by hand.',
                ['mechanise', 'script'], ['photograph', 'decorate', 'applaud']],
        ];
    }

    private static function businessAndFinance(): array
    {
        return [
            ['revenue', 'noun', 'the total money a business earns from selling goods or services',
                "The company's revenue grew by 20% after it launched the mobile app.",
                ['sales income', 'turnover'], ['temperature', 'tuition', 'altitude']],
            ['budget', 'noun', 'a plan for how much money will be earned and spent',
                'We cannot hire anyone new because the budget for this year is already used up.',
                ['spending plan', 'allocation'], ['ceremony', 'landscape', 'vacancy']],
            ['expenditure', 'noun', 'the total amount of money that is spent',
                "Rising fuel prices have pushed the company's monthly expenditure above its income.",
                ['spending', 'outlay'], ['elevation', 'literacy', 'retirement']],
            ['liability', 'noun', 'a debt or legal responsibility that a business must deal with',
                'The biggest liability on the balance sheet is the bank loan the company must repay next year.',
                ['debt', 'obligation'], ['asset', 'income', 'profit']],
            ['asset', 'noun', 'something valuable that a person or company owns',
                "The warehouse is the company's most valuable asset because it could be sold for a high price.",
                ['valuable possession', 'resource'], ['debt', 'complaint', 'penalty'],
                null, 'In everyday English, a useful skill or quality can also be "an asset".'],
            ['forecast', 'noun', 'a prediction of what will probably happen in the future',
                "The sales forecast for next quarter is based on this year's trends.",
                ['prediction', 'projection'], ['memory', 'receipt', 'souvenir']],
            ['stakeholder', 'noun', 'a person or group with an interest in how a project or business turns out',
                'Every stakeholder, from customers to investors, was invited to the review meeting.',
                ['interested party', 'investor or partner'], ['bystander', 'landlord', 'competitor']],
            ['procurement', 'noun', 'the process of buying goods or services for an organisation',
                "The procurement team compared three suppliers before buying the new laptops.",
                ['purchasing', 'sourcing'], ['recruitment', 'marketing', 'litigation']],
            ['invoice', 'noun', 'a document that lists what was supplied and asks for payment',
                'The vendor sent the invoice for the software licences, due within thirty days.',
                ['bill', 'statement of charges'], ['diary', 'brochure', 'certificate']],
            ['venture', 'noun', 'a new business activity that involves some risk',
                'Her first venture, an online tutoring platform, broke even in a year.',
                ['enterprise', 'undertaking'], ['holiday', 'tradition', 'routine']],
            ['acquisition', 'noun', 'the act of one company buying another company or a large part of it',
                "The acquisition of the smaller startup doubled the company's customer base.",
                ['takeover', 'purchase of a company'], ['resignation', 'inspection', 'festival']],
            ['audit', 'noun', "an official check of a company's accounts to make sure they are correct",
                'The annual audit found no errors in the financial statements.',
                ['inspection of accounts', 'review of accounts'], ['picnic', 'campaign', 'reunion']],
            ['compliance', 'noun', 'the act of following rules, laws or standards',
                'Compliance with data-protection laws is mandatory for every company that stores customer details.',
                ['conformity', 'adherence'], ['defiance', 'ambition', 'generosity']],
            ['incentive', 'noun', 'something offered to motivate people to do more or to do something',
                'The company offers a cash incentive to employees who refer a good candidate.',
                ['motivation', 'reward'], ['obstacle', 'warning', 'excuse']],
            ['subsidy', 'noun', 'money given by a government to help keep the price of something low',
                'A government subsidy made solar panels affordable for small farms.',
                ['grant', 'public funding'], ['penalty', 'tax return', 'fine']],
            ['inflation', 'noun', 'a general rise in prices over time, so money buys less',
                'With inflation at 7%, the same groceries cost much more than last year.',
                ['price rise', 'rising prices'], ['temperature', 'hesitation', 'migration']],
            ['dividend', 'noun', "a share of a company's profit paid to its shareholders",
                'Shareholders received a dividend of five rupees per share this year.',
                ['profit share', 'payout'], ['complaint', 'salary', 'rent']],
            ['warranty', 'noun', 'a written promise by a company to repair or replace a faulty product',
                'The laptop has a two-year warranty, so the repair will not cost us anything.',
                ['guarantee', 'assurance'], ['receipt', 'discount', 'catalogue']],
            ['royalty', 'noun', 'a payment made to a creator each time their work is sold or used',
                'The author earns a royalty on every copy of her book that is sold.',
                ['author payment', 'creator fee'], ['holiday', 'tuition', 'pension']],
            ['margin', 'noun', 'the amount of profit left after the cost of making something is taken from its selling price',
                'After the 40% discount, the shop was left with almost no margin on each sale.',
                ['profit gap', 'markup'], ['ceremony', 'altitude', 'humidity']],
        ];
    }

    private static function confusingPairs(): array
    {
        return [
            ['affect', 'verb', 'to change or influence something',
                'Heavy rain can affect the delivery schedule.',
                ['influence', 'change'], ['effect', 'infect', 'defect'], 'effect',
                'Affect is usually the verb; effect is usually the noun. Remember: A for Action, E for End result.'],
            ['effect', 'noun', 'a change that is caused by something',
                'The new policy had a positive effect on sales.',
                ['result', 'consequence'], ['affect', 'defect', 'reflect'], 'affect'],
            ['principal', 'noun', 'the head of a school or college',
                'The principal announced the placement drive during the morning assembly.',
                ['head teacher', 'dean'], ['principle', 'particle', 'pretext'], 'principle',
                'As an adjective, principal means main: the principal reason.'],
            ['principle', 'noun', 'a basic rule or belief that guides your behaviour',
                'I follow the principle of never sharing my password.',
                ['rule', 'belief'], ['principal', 'privilege', 'pension'], 'principal',
                'Memory trick: a princip-LE is a ru-LE.'],
            ['complement', 'verb', 'to go well with something and make it better',
                'Her design skills complement his coding skills perfectly.',
                ['go well with', 'round off'], ['compliment', 'implement', 'complain'], 'compliment',
                'Complement has an E for "complete": the two things complete each other.'],
            ['compliment', 'noun', 'a polite remark that praises someone',
                'My manager paid me a compliment on my presentation.',
                ['praise', 'kind remark'], ['complement', 'compliance', 'complaint'], 'complement',
                'Compliment has an I, like "I like it".'],
            ['advice', 'noun', 'an opinion about what someone should do',
                'My mentor gave me useful advice about negotiating a salary.',
                ['guidance', 'recommendation'], ['advise', 'device', 'advance'], 'advise',
                'Uncountable: say "a piece of advice".'],
            ['advise', 'verb', 'to tell someone what you think they should do',
                'I advise you to read the offer letter carefully before signing.',
                ['recommend', 'counsel'], ['advice', 'device', 'advance'], 'advice',
                'Advice is the noun (with a C, like "ice"); advise is the verb (with an S).'],
            ['accept', 'verb', 'to take something that is offered to you',
                'I was thrilled to accept the job offer and sign the contract the same day.',
                ['take', 'agree to'], ['except', 'expect', 'excerpt'], 'except'],
            ['except', 'preposition', 'not including; apart from',
                'Everyone attended the workshop except Rahul, who was ill.',
                ['apart from', 'excluding'], ['accept', 'expect', 'excerpt'], 'accept'],
            ['stationary', 'adjective', 'not moving',
                'The train was stationary for an hour because of a signal failure.',
                ['motionless', 'still'], ['stationery', 'strategic', 'spacious'], 'stationery',
                'Stationary has an A, like "stand": it stands still.'],
            ['stationery', 'noun', 'paper, pens and other things used for writing in an office',
                'The office orders stationery such as pens, notebooks and folders every month.',
                ['office supplies', 'writing materials'], ['stationary', 'strategy', 'statistics'], 'stationary',
                'Stationery with an E is for Envelopes.'],
            ['lose', 'verb', 'to no longer have something, or to fail to keep it',
                'Always back up your files so you never lose your work.',
                ['misplace', 'fail to keep'], ['loose', 'choose', 'loss'], 'loose',
                'Lose has one O; loose has two — a loose thing has more room.'],
            ['loose', 'adjective', 'not tight, or not firmly fixed in place',
                'The screw was loose, so the laptop hinge wobbled.',
                ['slack', 'unfastened'], ['lose', 'loss', 'lease'], 'lose'],
            ['then', 'adverb', 'after that, or at that time',
                'Finish the aptitude section first, then move on to the coding round.',
                ['next', 'afterwards'], ['than', 'there', 'when'], 'than',
                'Then is about time; than is for comparing.', 'beginner'],
            ['than', 'conjunction', 'a word used to compare two things',
                'The new laptop is faster than my old one.',
                ['compared with'], ['then', 'that', 'there'], 'then',
                null, 'beginner'],
            ['its', 'determiner', 'belonging to it',
                'The company announced its results on Friday.',
                ['of it'], ["it's", 'his', 'hers'], "it's",
                'No apostrophe: its is possessive, like his and hers.', 'beginner'],
            ["it's", 'contraction', "short for 'it is' or 'it has'",
                "It's important to reply to recruiters within a day.",
                ['it is', 'it has'], ['its', 'his', 'hers'], 'its',
                "If you can say \"it is\" in its place, you need the apostrophe.", 'beginner'],
            ['farther', 'adverb', 'at a greater physical distance',
                'My college is farther from the city than yours.',
                ['more distant', 'at a longer distance'], ['further', 'farmer', 'faster'], 'further',
                'Farther is for distance you can measure; further is for degree or extra.'],
            ['further', 'adjective', 'more, or additional',
                'Please contact HR for further details about the stipend.',
                ['additional', 'extra'], ['farther', 'father', 'fewer'], 'farther'],
        ];
    }

    private static function phrasalVerbsAndIdioms(): array
    {
        return [
            ['follow up', 'phrasal verb', 'to contact someone again about something you discussed earlier',
                "I will follow up with the recruiter if I don't hear back by Friday.",
                ['chase', 'check back'], ['look after', 'give up', 'turn down'],
                null, 'The noun is "follow-up" with a hyphen: a follow-up email.'],
            ['carry out', 'phrasal verb', 'to perform or conduct a task, test or study',
                'Our team will carry out the survey next week.',
                ['perform', 'conduct'], ['stand for', 'drop by', 'fall behind']],
            ['set up', 'phrasal verb', 'to arrange or prepare something so it is ready to use',
                'Can you set up a meeting with the client for Monday?',
                ['arrange', 'organise'], ['turn off', 'break down', 'pull out']],
            ['look into', 'phrasal verb', 'to investigate something carefully',
                'The IT team will look into the login problem and update you today.',
                ['investigate', 'examine'], ['run out of', 'put up with', 'get along']],
            ['step down', 'phrasal verb', 'to leave an important job or position',
                'The CEO decided to step down after fifteen years leading the company.',
                ['resign', 'quit a post'], ['speed up', 'show off', 'warm up']],
            ['drop by', 'phrasal verb', 'to visit briefly, without a fixed plan',
                'Feel free to drop by my desk if you have any doubts about the task.',
                ['pop in', 'visit briefly'], ['look after', 'turn down', 'break down']],
            ['wrap up', 'phrasal verb', 'to bring something to an end',
                "Let's wrap up the meeting now so everyone can leave on time.",
                ['finish', 'conclude'], ['break in', 'pass out', 'bring up']],
            ['keep an eye on', 'phrase', 'to watch something carefully over a period of time',
                'Please keep an eye on the server logs while I am in the meeting.',
                ['monitor', 'watch'], ['look up to', 'get rid of', 'make up for']],
            ['come up with', 'phrasal verb', 'to think of an idea or plan',
                'We need to come up with a creative solution before the demo.',
                ['think of', 'devise'], ['put up with', 'catch up with', 'run out of']],
            ['back up', 'phrasal verb', 'to make a copy of data in case the original is lost',
                'Remember to back up your project files before you format the laptop.',
                ['save a copy of', 'duplicate'], ['log in', 'shut down', 'cut off'],
                null, 'The noun is one word: a backup.'],
            ['figure out', 'phrasal verb', 'to understand or solve something after thinking about it',
                'It took me an hour to figure out why the code was crashing.',
                ['work out', 'make sense of'], ['hand out', 'pass away', 'black out']],
            ['hold on', 'phrasal verb', 'to wait for a short time',
                'Please hold on while I transfer your call to the manager.',
                ['wait', 'hang on'], ['pick out', 'pass by', 'turn into']],
            ['take over', 'phrasal verb', 'to take control or responsibility from someone else',
                'Priya will take over the project when I go on leave.',
                ['assume control of', 'replace'], ['pull over', 'cheer up', 'calm down']],
            ['run into', 'phrasal verb', 'to meet someone by chance',
                'You might run into your future boss at a networking event, so be prepared.',
                ['bump into', 'meet by chance'], ['cut down on', 'make up for', 'hang out']],
            ['fall behind', 'phrasal verb', 'to fail to keep up with others or with a schedule',
                'If you skip daily practice, you will fall behind your batchmates.',
                ['lag', 'trail'], ['come across', 'stay up', 'take after']],
            ['bring up', 'phrasal verb', 'to mention a subject for discussion',
                "Don't bring up salary in the first round unless the recruiter asks.",
                ['raise', 'mention'], ['pick on', 'cut off', 'hold out']],
            ['call off', 'phrasal verb', 'to cancel something that was planned',
                'The organisers had to call off the event because of heavy rain.',
                ['cancel', 'scrap'], ['put on', 'turn in', 'pull through']],
            ['burn the midnight oil', 'idiom', 'to work late into the night',
                'Before the deadline, the whole team had to burn the midnight oil.',
                ['work late', 'stay up working'], ['break the ice', 'spill the beans', 'miss the boat']],
            ['break the ice', 'idiom', 'to say or do something that makes people feel relaxed at a first meeting',
                'A simple joke can break the ice at the start of a group discussion.',
                ['start a conversation', 'ease the tension'], ['burn the midnight oil', 'spill the beans', 'hit the road']],
            ['on the same page', 'idiom', 'having the same understanding of a situation',
                "Before we start coding, let's make sure we are all on the same page.",
                ['in agreement', 'aligned'], ['on thin ice', 'in hot water', 'over the moon']],
        ];
    }

    private static function reasoningAndVerbal(): array
    {
        return [
            ['ubiquitous', 'adjective', 'seeming to be present everywhere',
                'Smartphones are so ubiquitous that it is hard to find a classroom without one.',
                ['omnipresent', 'everywhere'], ['scarce', 'obsolete', 'negligible']],
            ['mitigate', 'verb', 'to make something less severe or harmful',
                'Regular backups can mitigate the damage if a server fails.',
                ['reduce', 'lessen'], ['aggravate', 'inflict', 'ignore'],
                null, 'Often confused with "militate" (to work against) — they are unrelated.'],
            ['ambivalent', 'adjective', 'having mixed feelings about something',
                'She felt ambivalent about the job offer: the salary was great but the commute was long.',
                ['torn', 'of two minds'], ['ecstatic', 'furious', 'confident']],
            ['inevitable', 'adjective', 'certain to happen and impossible to avoid',
                'With so many applicants, some disappointment was inevitable.',
                ['unavoidable', 'certain'], ['avoidable', 'unlikely', 'pleasant']],
            ['substantiate', 'verb', 'to provide evidence that shows a claim is true',
                'You must substantiate your claim with data, not just opinions.',
                ['back up with evidence', 'prove'], ['decorate', 'imitate', 'abandon']],
            ['plausible', 'adjective', 'seeming reasonable and likely to be true',
                'His excuse sounded plausible, but the records showed he had lied.',
                ['believable', 'credible'], ['ridiculous', 'absurd', 'careless']],
            ['inherent', 'adjective', 'existing as a natural and permanent part of something',
                'Every investment carries some inherent risk that no one can remove completely.',
                ['built-in', 'intrinsic'], ['optional', 'temporary', 'imaginary']],
            ['discrepancy', 'noun', 'a difference between things that ought to be the same',
                'The auditor found a discrepancy between the invoice total and the payment received.',
                ['mismatch', 'inconsistency'], ['celebration', 'compliment', 'tradition']],
            ['pragmatic', 'adjective', 'dealing with things in a practical, realistic way',
                'Our manager is very pragmatic: she picks the solution that works today instead of waiting for a perfect one.',
                ['practical', 'realistic'], ['idealistic', 'sentimental', 'stubborn']],
            ['exacerbate', 'verb', 'to make a bad situation worse',
                'Skipping meals before the exam will only exacerbate your stress.',
                ['aggravate', 'worsen'], ['relieve', 'mitigate', 'postpone']],
            ['volatile', 'adjective', 'likely to change suddenly and unpredictably',
                'Share prices are volatile, so they can rise or fall sharply in a single day.',
                ['unstable', 'erratic'], ['stable', 'predictable', 'steady']],
            ['arbitrary', 'adjective', 'decided by chance or whim rather than by a reason',
                'Choosing candidates by their birthday is arbitrary and unfair.',
                ['random', 'capricious'], ['reasonable', 'logical', 'scientific']],
            ['tangible', 'adjective', 'real and clear enough to be seen or measured',
                'The project produced tangible results: sales rose by 12% in one quarter.',
                ['concrete', 'measurable'], ['imaginary', 'hypothetical', 'invisible']],
            ['comprehensive', 'adjective', 'including everything that is needed; complete',
                'The handbook gives a comprehensive guide to every policy in the company.',
                ['thorough', 'all-inclusive'], ['partial', 'shallow', 'secret']],
            ['hypothesis', 'noun', 'an idea suggested as an explanation that has yet to be tested',
                'Our hypothesis is that shorter emails get faster replies, so we will test it.',
                ['theory', 'assumption'], ['conclusion', 'guarantee', 'verdict']],
            ['advocate', 'verb', 'to publicly support an idea or plan',
                'I advocate flexible work hours because they improve focus and morale.',
                ['champion', 'support'], ['oppose', 'resist', 'dismiss'],
                null, 'As a noun it means a supporter, or a lawyer in some countries.'],
            ['deter', 'verb', 'to make someone decide not to do something',
                'Strict penalties deter students from copying in exams.',
                ['discourage', 'put off'], ['encourage', 'invite', 'allow']],
            ['benevolent', 'adjective', 'kind, generous and wanting to help others',
                'The benevolent donor paid the tuition fees of fifty students.',
                ['kind-hearted', 'charitable'], ['greedy', 'hostile', 'selfish']],
            ['obsolete', 'adjective', 'no longer used because something newer has replaced it',
                'Floppy disks became obsolete once USB drives could hold far more data.',
                ['outdated', 'out of use'], ['popular', 'essential', 'fashionable']],
            ['frugal', 'adjective', 'careful about spending money; not wasteful',
                'Because she was frugal, she saved half of her first salary.',
                ['thrifty', 'economical'], ['extravagant', 'wasteful', 'careless']],
        ];
    }
}
